// File generated from our OpenAPI spec by Stainless.

package com.openlayer.api.models.governance.rules

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.openlayer.api.core.JsonValue
import com.openlayer.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RuleCreateResponseTest {

    @Test
    fun create() {
        val ruleCreateResponse =
            RuleCreateResponse.builder()
                .id("7c9a1e2b-3d4f-4a5b-8c6d-7e8f9a0b1c2d")
                .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                .name("Monitoring enabled")
                .scope(RuleCreateResponse.Scope.PROJECT)
                .type(RuleCreateResponse.Type.PLATFORM)
                .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .automationParams(
                    RuleCreateResponse.AutomationParams.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .automationType("monitoring_mode_enabled")
                .deactivated(true)
                .description("Each project must have Openlayer monitoring mode enabled.")
                .evidenceType(RuleCreateResponse.EvidenceType.DOCUMENT)
                .addFramework(
                    RuleCreateResponse.Framework.builder()
                        .id("9f1b3c2d-4e5a-4f60-8a71-2b3c4d5e6f70")
                        .avatar(
                            RuleCreateResponse.Framework.Avatar.builder()
                                .type(RuleCreateResponse.Framework.Avatar.Type.EMOJI)
                                .value("🧭")
                                .build()
                        )
                        .builtInSlug("eu_ai_act")
                        .enabled(true)
                        .name("EU AI Act")
                        .build()
                )
                .immutable(true)
                .renewalCadenceDays(90L)
                .addResult(
                    RuleCreateResponse.Result.builder()
                        .id("5b7d9f1a-2c3e-4d5f-8a6b-9c0d1e2f3a4b")
                        .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .deactivated(true)
                        .ruleId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .status(RuleCreateResponse.Result.Status.PASSING)
                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addBlockedBy(
                            RuleCreateResponse.Result.BlockedBy.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .status(RuleCreateResponse.Result.BlockedBy.Status.PASSING)
                                .build()
                        )
                        .addBlocking(
                            RuleCreateResponse.Result.Blocking.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .status(RuleCreateResponse.Result.Blocking.Status.PASSING)
                                .build()
                        )
                        .dateLastEvaluated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfLatestEvidence(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfNextEvaluation(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfRenewal(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .deactivatedReason("deactivatedReason")
                        .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .statusMessage("statusMessage")
                        .build()
                )
                .resultsSummary(
                    RuleCreateResponse.ResultsSummary.builder().passing(0L).total(0L).build()
                )
                .addTagId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addTag(
                    RuleCreateResponse.Tag.builder()
                        .id("6e8a0c2d-4f5b-4a3c-9d7e-8f0a1b2c3d4e")
                        .creatorId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .immutable(true)
                        .name("Evaluation")
                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .color("color")
                        .build()
                )
                .build()

        assertThat(ruleCreateResponse.id()).isEqualTo("7c9a1e2b-3d4f-4a5b-8c6d-7e8f9a0b1c2d")
        assertThat(ruleCreateResponse.dateCreated())
            .isEqualTo(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
        assertThat(ruleCreateResponse.dateUpdated())
            .isEqualTo(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
        assertThat(ruleCreateResponse.name()).isEqualTo("Monitoring enabled")
        assertThat(ruleCreateResponse.scope()).isEqualTo(RuleCreateResponse.Scope.PROJECT)
        assertThat(ruleCreateResponse.type()).isEqualTo(RuleCreateResponse.Type.PLATFORM)
        assertThat(ruleCreateResponse.workspaceId())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(ruleCreateResponse.assigneeId()).contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(ruleCreateResponse.automationParams())
            .contains(
                RuleCreateResponse.AutomationParams.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(ruleCreateResponse.automationType()).contains("monitoring_mode_enabled")
        assertThat(ruleCreateResponse.deactivated()).contains(true)
        assertThat(ruleCreateResponse.description())
            .contains("Each project must have Openlayer monitoring mode enabled.")
        assertThat(ruleCreateResponse.evidenceType())
            .contains(RuleCreateResponse.EvidenceType.DOCUMENT)
        assertThat(ruleCreateResponse.frameworks().getOrNull())
            .containsExactly(
                RuleCreateResponse.Framework.builder()
                    .id("9f1b3c2d-4e5a-4f60-8a71-2b3c4d5e6f70")
                    .avatar(
                        RuleCreateResponse.Framework.Avatar.builder()
                            .type(RuleCreateResponse.Framework.Avatar.Type.EMOJI)
                            .value("🧭")
                            .build()
                    )
                    .builtInSlug("eu_ai_act")
                    .enabled(true)
                    .name("EU AI Act")
                    .build()
            )
        assertThat(ruleCreateResponse.immutable()).contains(true)
        assertThat(ruleCreateResponse.renewalCadenceDays()).contains(90L)
        assertThat(ruleCreateResponse.results().getOrNull())
            .containsExactly(
                RuleCreateResponse.Result.builder()
                    .id("5b7d9f1a-2c3e-4d5f-8a6b-9c0d1e2f3a4b")
                    .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                    .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                    .deactivated(true)
                    .ruleId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .status(RuleCreateResponse.Result.Status.PASSING)
                    .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addBlockedBy(
                        RuleCreateResponse.Result.BlockedBy.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .status(RuleCreateResponse.Result.BlockedBy.Status.PASSING)
                            .build()
                    )
                    .addBlocking(
                        RuleCreateResponse.Result.Blocking.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .status(RuleCreateResponse.Result.Blocking.Status.PASSING)
                            .build()
                    )
                    .dateLastEvaluated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateOfLatestEvidence(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateOfNextEvaluation(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateOfRenewal(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .deactivatedReason("deactivatedReason")
                    .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .statusMessage("statusMessage")
                    .build()
            )
        assertThat(ruleCreateResponse.resultsSummary())
            .contains(RuleCreateResponse.ResultsSummary.builder().passing(0L).total(0L).build())
        assertThat(ruleCreateResponse.tagIds().getOrNull())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(ruleCreateResponse.tags().getOrNull())
            .containsExactly(
                RuleCreateResponse.Tag.builder()
                    .id("6e8a0c2d-4f5b-4a3c-9d7e-8f0a1b2c3d4e")
                    .creatorId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                    .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                    .immutable(true)
                    .name("Evaluation")
                    .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .color("color")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val ruleCreateResponse =
            RuleCreateResponse.builder()
                .id("7c9a1e2b-3d4f-4a5b-8c6d-7e8f9a0b1c2d")
                .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                .name("Monitoring enabled")
                .scope(RuleCreateResponse.Scope.PROJECT)
                .type(RuleCreateResponse.Type.PLATFORM)
                .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .automationParams(
                    RuleCreateResponse.AutomationParams.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .automationType("monitoring_mode_enabled")
                .deactivated(true)
                .description("Each project must have Openlayer monitoring mode enabled.")
                .evidenceType(RuleCreateResponse.EvidenceType.DOCUMENT)
                .addFramework(
                    RuleCreateResponse.Framework.builder()
                        .id("9f1b3c2d-4e5a-4f60-8a71-2b3c4d5e6f70")
                        .avatar(
                            RuleCreateResponse.Framework.Avatar.builder()
                                .type(RuleCreateResponse.Framework.Avatar.Type.EMOJI)
                                .value("🧭")
                                .build()
                        )
                        .builtInSlug("eu_ai_act")
                        .enabled(true)
                        .name("EU AI Act")
                        .build()
                )
                .immutable(true)
                .renewalCadenceDays(90L)
                .addResult(
                    RuleCreateResponse.Result.builder()
                        .id("5b7d9f1a-2c3e-4d5f-8a6b-9c0d1e2f3a4b")
                        .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .deactivated(true)
                        .ruleId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .status(RuleCreateResponse.Result.Status.PASSING)
                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addBlockedBy(
                            RuleCreateResponse.Result.BlockedBy.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .status(RuleCreateResponse.Result.BlockedBy.Status.PASSING)
                                .build()
                        )
                        .addBlocking(
                            RuleCreateResponse.Result.Blocking.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .status(RuleCreateResponse.Result.Blocking.Status.PASSING)
                                .build()
                        )
                        .dateLastEvaluated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfLatestEvidence(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfNextEvaluation(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfRenewal(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .deactivatedReason("deactivatedReason")
                        .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .statusMessage("statusMessage")
                        .build()
                )
                .resultsSummary(
                    RuleCreateResponse.ResultsSummary.builder().passing(0L).total(0L).build()
                )
                .addTagId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addTag(
                    RuleCreateResponse.Tag.builder()
                        .id("6e8a0c2d-4f5b-4a3c-9d7e-8f0a1b2c3d4e")
                        .creatorId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .immutable(true)
                        .name("Evaluation")
                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .color("color")
                        .build()
                )
                .build()

        val roundtrippedRuleCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(ruleCreateResponse),
                jacksonTypeRef<RuleCreateResponse>(),
            )

        assertThat(roundtrippedRuleCreateResponse).isEqualTo(ruleCreateResponse)
    }
}
