// File generated from our OpenAPI spec by Stainless.

package com.openlayer.api.models.governance.rules

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.openlayer.api.core.JsonValue
import com.openlayer.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RuleUpdateResponseTest {

    @Test
    fun create() {
        val ruleUpdateResponse =
            RuleUpdateResponse.builder()
                .id("7c9a1e2b-3d4f-4a5b-8c6d-7e8f9a0b1c2d")
                .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                .name("Monitoring enabled")
                .scope(RuleUpdateResponse.Scope.PROJECT)
                .type(RuleUpdateResponse.Type.PLATFORM)
                .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .automationParams(
                    RuleUpdateResponse.AutomationParams.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .automationType("monitoring_mode_enabled")
                .deactivated(true)
                .description("Each project must have Openlayer monitoring mode enabled.")
                .evidenceType(RuleUpdateResponse.EvidenceType.DOCUMENT)
                .addFramework(
                    RuleUpdateResponse.Framework.builder()
                        .id("9f1b3c2d-4e5a-4f60-8a71-2b3c4d5e6f70")
                        .avatar(
                            RuleUpdateResponse.Framework.Avatar.builder()
                                .type(RuleUpdateResponse.Framework.Avatar.Type.EMOJI)
                                .value("🧭")
                                .build()
                        )
                        .builtInSlug("eu_ai_act")
                        .enabled(true)
                        .name("EU AI Act")
                        .build()
                )
                .immutable(true)
                .renewalCadenceDays(90L)
                .addResult(
                    RuleUpdateResponse.Result.builder()
                        .id("5b7d9f1a-2c3e-4d5f-8a6b-9c0d1e2f3a4b")
                        .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .deactivated(true)
                        .ruleId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .status(RuleUpdateResponse.Result.Status.PASSING)
                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addBlockedBy(
                            RuleUpdateResponse.Result.BlockedBy.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .status(RuleUpdateResponse.Result.BlockedBy.Status.PASSING)
                                .build()
                        )
                        .addBlocking(
                            RuleUpdateResponse.Result.Blocking.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .status(RuleUpdateResponse.Result.Blocking.Status.PASSING)
                                .build()
                        )
                        .dateLastEvaluated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfLatestEvidence(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfNextEvaluation(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfRenewal(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .deactivatedReason("deactivatedReason")
                        .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .statusMessage("statusMessage")
                        .build()
                )
                .resultsSummary(
                    RuleUpdateResponse.ResultsSummary.builder().passing(0L).total(0L).build()
                )
                .addTagId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addTag(
                    RuleUpdateResponse.Tag.builder()
                        .id("6e8a0c2d-4f5b-4a3c-9d7e-8f0a1b2c3d4e")
                        .creatorId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .immutable(true)
                        .name("Evaluation")
                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .color("color")
                        .build()
                )
                .build()

        assertThat(ruleUpdateResponse.id()).isEqualTo("7c9a1e2b-3d4f-4a5b-8c6d-7e8f9a0b1c2d")
        assertThat(ruleUpdateResponse.dateCreated())
            .isEqualTo(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
        assertThat(ruleUpdateResponse.dateUpdated())
            .isEqualTo(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
        assertThat(ruleUpdateResponse.name()).isEqualTo("Monitoring enabled")
        assertThat(ruleUpdateResponse.scope()).isEqualTo(RuleUpdateResponse.Scope.PROJECT)
        assertThat(ruleUpdateResponse.type()).isEqualTo(RuleUpdateResponse.Type.PLATFORM)
        assertThat(ruleUpdateResponse.workspaceId())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(ruleUpdateResponse.assigneeId()).contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(ruleUpdateResponse.automationParams())
            .contains(
                RuleUpdateResponse.AutomationParams.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(ruleUpdateResponse.automationType()).contains("monitoring_mode_enabled")
        assertThat(ruleUpdateResponse.deactivated()).contains(true)
        assertThat(ruleUpdateResponse.description())
            .contains("Each project must have Openlayer monitoring mode enabled.")
        assertThat(ruleUpdateResponse.evidenceType())
            .contains(RuleUpdateResponse.EvidenceType.DOCUMENT)
        assertThat(ruleUpdateResponse.frameworks().getOrNull())
            .containsExactly(
                RuleUpdateResponse.Framework.builder()
                    .id("9f1b3c2d-4e5a-4f60-8a71-2b3c4d5e6f70")
                    .avatar(
                        RuleUpdateResponse.Framework.Avatar.builder()
                            .type(RuleUpdateResponse.Framework.Avatar.Type.EMOJI)
                            .value("🧭")
                            .build()
                    )
                    .builtInSlug("eu_ai_act")
                    .enabled(true)
                    .name("EU AI Act")
                    .build()
            )
        assertThat(ruleUpdateResponse.immutable()).contains(true)
        assertThat(ruleUpdateResponse.renewalCadenceDays()).contains(90L)
        assertThat(ruleUpdateResponse.results().getOrNull())
            .containsExactly(
                RuleUpdateResponse.Result.builder()
                    .id("5b7d9f1a-2c3e-4d5f-8a6b-9c0d1e2f3a4b")
                    .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                    .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                    .deactivated(true)
                    .ruleId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .status(RuleUpdateResponse.Result.Status.PASSING)
                    .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addBlockedBy(
                        RuleUpdateResponse.Result.BlockedBy.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .status(RuleUpdateResponse.Result.BlockedBy.Status.PASSING)
                            .build()
                    )
                    .addBlocking(
                        RuleUpdateResponse.Result.Blocking.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .status(RuleUpdateResponse.Result.Blocking.Status.PASSING)
                            .build()
                    )
                    .dateLastEvaluated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateOfLatestEvidence(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateOfNextEvaluation(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateOfRenewal(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .deactivatedReason("deactivatedReason")
                    .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .statusMessage("statusMessage")
                    .build()
            )
        assertThat(ruleUpdateResponse.resultsSummary())
            .contains(RuleUpdateResponse.ResultsSummary.builder().passing(0L).total(0L).build())
        assertThat(ruleUpdateResponse.tagIds().getOrNull())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(ruleUpdateResponse.tags().getOrNull())
            .containsExactly(
                RuleUpdateResponse.Tag.builder()
                    .id("6e8a0c2d-4f5b-4a3c-9d7e-8f0a1b2c3d4e")
                    .creatorId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                    .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                    .immutable(true)
                    .name("Evaluation")
                    .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .color("color")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val ruleUpdateResponse =
            RuleUpdateResponse.builder()
                .id("7c9a1e2b-3d4f-4a5b-8c6d-7e8f9a0b1c2d")
                .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                .name("Monitoring enabled")
                .scope(RuleUpdateResponse.Scope.PROJECT)
                .type(RuleUpdateResponse.Type.PLATFORM)
                .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .automationParams(
                    RuleUpdateResponse.AutomationParams.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .automationType("monitoring_mode_enabled")
                .deactivated(true)
                .description("Each project must have Openlayer monitoring mode enabled.")
                .evidenceType(RuleUpdateResponse.EvidenceType.DOCUMENT)
                .addFramework(
                    RuleUpdateResponse.Framework.builder()
                        .id("9f1b3c2d-4e5a-4f60-8a71-2b3c4d5e6f70")
                        .avatar(
                            RuleUpdateResponse.Framework.Avatar.builder()
                                .type(RuleUpdateResponse.Framework.Avatar.Type.EMOJI)
                                .value("🧭")
                                .build()
                        )
                        .builtInSlug("eu_ai_act")
                        .enabled(true)
                        .name("EU AI Act")
                        .build()
                )
                .immutable(true)
                .renewalCadenceDays(90L)
                .addResult(
                    RuleUpdateResponse.Result.builder()
                        .id("5b7d9f1a-2c3e-4d5f-8a6b-9c0d1e2f3a4b")
                        .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .deactivated(true)
                        .ruleId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .status(RuleUpdateResponse.Result.Status.PASSING)
                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .assigneeId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addBlockedBy(
                            RuleUpdateResponse.Result.BlockedBy.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .status(RuleUpdateResponse.Result.BlockedBy.Status.PASSING)
                                .build()
                        )
                        .addBlocking(
                            RuleUpdateResponse.Result.Blocking.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .status(RuleUpdateResponse.Result.Blocking.Status.PASSING)
                                .build()
                        )
                        .dateLastEvaluated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfLatestEvidence(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfNextEvaluation(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateOfRenewal(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .deactivatedReason("deactivatedReason")
                        .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .statusMessage("statusMessage")
                        .build()
                )
                .resultsSummary(
                    RuleUpdateResponse.ResultsSummary.builder().passing(0L).total(0L).build()
                )
                .addTagId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addTag(
                    RuleUpdateResponse.Tag.builder()
                        .id("6e8a0c2d-4f5b-4a3c-9d7e-8f0a1b2c3d4e")
                        .creatorId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .dateCreated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2026-03-22T11:31:01.185Z"))
                        .immutable(true)
                        .name("Evaluation")
                        .workspaceId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .color("color")
                        .build()
                )
                .build()

        val roundtrippedRuleUpdateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(ruleUpdateResponse),
                jacksonTypeRef<RuleUpdateResponse>(),
            )

        assertThat(roundtrippedRuleUpdateResponse).isEqualTo(ruleUpdateResponse)
    }
}
