// File generated from our OpenAPI spec by Stainless.

package com.openlayer.api.models.inferencepipelines

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.openlayer.api.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InferencePipelineRetrieveResponseTest {

    @Test
    fun create() {
        val inferencePipelineRetrieveResponse =
            InferencePipelineRetrieveResponse.builder()
                .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .dateLastEvaluated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .dateLastSampleReceived(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .dateOfNextEvaluation(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .description("This pipeline is used for production.")
                .failingGoalCount(1L)
                .links(
                    InferencePipelineRetrieveResponse.Links.builder()
                        .app(
                            "https://app.openlayer.com/myWorkspace/3fa85f64-5717-4562-b3fc-2c963f66afa6/inference-pipeline/3fa85f64-5717-4562-b3fc-2c963f66afa6"
                        )
                        .build()
                )
                .name("production")
                .passingGoalCount(5L)
                .projectId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                .status(InferencePipelineRetrieveResponse.Status.COMPLETED)
                .statusMessage("Tests successfully evaluated")
                .totalGoalCount(6L)
                .dataBackend(
                    InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend.builder()
                        .backendType(
                            InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend
                                .BackendType
                                .BIGQUERY
                        )
                        .bigqueryConnectionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .config(
                            InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend.Config
                                .builder()
                                .groundTruthColumnName("ground_truth")
                                .humanFeedbackColumnName("human_feedback")
                                .inferenceIdColumnName("id")
                                .latencyColumnName("latency")
                                .timestampColumnName("timestamp")
                                .build()
                        )
                        .datasetId("my-dataset")
                        .projectId("my-project")
                        .tableId("my-table")
                        .partitionType(
                            InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend
                                .PartitionType
                                .DAY
                        )
                        .build()
                )
                .dateLastPolled(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .project(
                    InferencePipelineRetrieveResponse.Project.builder()
                        .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .creatorId("589ece63-49a2-41b4-98e1-10547761d4b0")
                        .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .developmentGoalCount(5L)
                        .goalCount(10L)
                        .inferencePipelineCount(1L)
                        .links(
                            InferencePipelineRetrieveResponse.Project.Links.builder()
                                .app(
                                    "https://app.openlayer.com/myWorkspace/3fa85f64-5717-4562-b3fc-2c963f66afa6"
                                )
                                .build()
                        )
                        .monitoringGoalCount(5L)
                        .name("My Project")
                        .source(InferencePipelineRetrieveResponse.Project.Source.WEB)
                        .taskType(InferencePipelineRetrieveResponse.Project.TaskType.LLM_BASE)
                        .versionCount(2L)
                        .workspaceId("055fddb1-261f-4654-8598-f6347ee46a09")
                        .description("My project description.")
                        .gitRepo(
                            InferencePipelineRetrieveResponse.Project.GitRepo.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .dateConnected(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .dateUpdated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .gitAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .gitId(0L)
                                .name("name")
                                .private_(true)
                                .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .slug("slug")
                                .url("url")
                                .branch("branch")
                                .rootDir("rootDir")
                                .build()
                        )
                        .build()
                )
                .totalRecordsCount(1000L)
                .workspace(
                    InferencePipelineRetrieveResponse.Workspace.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .creatorId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .dateCreated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateUpdated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .inviteCount(0L)
                        .memberCount(0L)
                        .name("Openlayer")
                        .periodEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .periodStartDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .projectCount(0L)
                        .slug("openlayer")
                        .status(InferencePipelineRetrieveResponse.Workspace.Status.ACTIVE)
                        .inviteCode("inviteCode")
                        .addMonthlyUsage(
                            InferencePipelineRetrieveResponse.Workspace.MonthlyUsage.builder()
                                .executionTimeMs(0L)
                                .monthYear(LocalDate.parse("2019-12-27"))
                                .predictionCount(0L)
                                .build()
                        )
                        .samlOnlyAccess(true)
                        .addWildcardDomain("string")
                        .build()
                )
                .workspaceId("055fddb1-261f-4654-8598-f6347ee46a09")
                .build()

        assertThat(inferencePipelineRetrieveResponse.id())
            .isEqualTo("3fa85f64-5717-4562-b3fc-2c963f66afa6")
        assertThat(inferencePipelineRetrieveResponse.dateCreated())
            .isEqualTo(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
        assertThat(inferencePipelineRetrieveResponse.dateLastEvaluated())
            .contains(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
        assertThat(inferencePipelineRetrieveResponse.dateLastSampleReceived())
            .contains(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
        assertThat(inferencePipelineRetrieveResponse.dateOfNextEvaluation())
            .contains(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
        assertThat(inferencePipelineRetrieveResponse.dateUpdated())
            .isEqualTo(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
        assertThat(inferencePipelineRetrieveResponse.description())
            .contains("This pipeline is used for production.")
        assertThat(inferencePipelineRetrieveResponse.failingGoalCount()).isEqualTo(1L)
        assertThat(inferencePipelineRetrieveResponse.links())
            .isEqualTo(
                InferencePipelineRetrieveResponse.Links.builder()
                    .app(
                        "https://app.openlayer.com/myWorkspace/3fa85f64-5717-4562-b3fc-2c963f66afa6/inference-pipeline/3fa85f64-5717-4562-b3fc-2c963f66afa6"
                    )
                    .build()
            )
        assertThat(inferencePipelineRetrieveResponse.name()).isEqualTo("production")
        assertThat(inferencePipelineRetrieveResponse.passingGoalCount()).isEqualTo(5L)
        assertThat(inferencePipelineRetrieveResponse.projectId())
            .isEqualTo("3fa85f64-5717-4562-b3fc-2c963f66afa6")
        assertThat(inferencePipelineRetrieveResponse.status())
            .isEqualTo(InferencePipelineRetrieveResponse.Status.COMPLETED)
        assertThat(inferencePipelineRetrieveResponse.statusMessage())
            .contains("Tests successfully evaluated")
        assertThat(inferencePipelineRetrieveResponse.totalGoalCount()).isEqualTo(6L)
        assertThat(inferencePipelineRetrieveResponse.dataBackend())
            .contains(
                InferencePipelineRetrieveResponse.DataBackend.ofBigQuery(
                    InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend.builder()
                        .backendType(
                            InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend
                                .BackendType
                                .BIGQUERY
                        )
                        .bigqueryConnectionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .config(
                            InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend.Config
                                .builder()
                                .groundTruthColumnName("ground_truth")
                                .humanFeedbackColumnName("human_feedback")
                                .inferenceIdColumnName("id")
                                .latencyColumnName("latency")
                                .timestampColumnName("timestamp")
                                .build()
                        )
                        .datasetId("my-dataset")
                        .projectId("my-project")
                        .tableId("my-table")
                        .partitionType(
                            InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend
                                .PartitionType
                                .DAY
                        )
                        .build()
                )
            )
        assertThat(inferencePipelineRetrieveResponse.dateLastPolled())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(inferencePipelineRetrieveResponse.project())
            .contains(
                InferencePipelineRetrieveResponse.Project.builder()
                    .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .creatorId("589ece63-49a2-41b4-98e1-10547761d4b0")
                    .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .developmentGoalCount(5L)
                    .goalCount(10L)
                    .inferencePipelineCount(1L)
                    .links(
                        InferencePipelineRetrieveResponse.Project.Links.builder()
                            .app(
                                "https://app.openlayer.com/myWorkspace/3fa85f64-5717-4562-b3fc-2c963f66afa6"
                            )
                            .build()
                    )
                    .monitoringGoalCount(5L)
                    .name("My Project")
                    .source(InferencePipelineRetrieveResponse.Project.Source.WEB)
                    .taskType(InferencePipelineRetrieveResponse.Project.TaskType.LLM_BASE)
                    .versionCount(2L)
                    .workspaceId("055fddb1-261f-4654-8598-f6347ee46a09")
                    .description("My project description.")
                    .gitRepo(
                        InferencePipelineRetrieveResponse.Project.GitRepo.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .dateConnected(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .dateUpdated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .gitAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .gitId(0L)
                            .name("name")
                            .private_(true)
                            .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .slug("slug")
                            .url("url")
                            .branch("branch")
                            .rootDir("rootDir")
                            .build()
                    )
                    .build()
            )
        assertThat(inferencePipelineRetrieveResponse.totalRecordsCount()).contains(1000L)
        assertThat(inferencePipelineRetrieveResponse.workspace())
            .contains(
                InferencePipelineRetrieveResponse.Workspace.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .creatorId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .dateCreated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dateUpdated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .inviteCount(0L)
                    .memberCount(0L)
                    .name("Openlayer")
                    .periodEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .periodStartDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .projectCount(0L)
                    .slug("openlayer")
                    .status(InferencePipelineRetrieveResponse.Workspace.Status.ACTIVE)
                    .inviteCode("inviteCode")
                    .addMonthlyUsage(
                        InferencePipelineRetrieveResponse.Workspace.MonthlyUsage.builder()
                            .executionTimeMs(0L)
                            .monthYear(LocalDate.parse("2019-12-27"))
                            .predictionCount(0L)
                            .build()
                    )
                    .samlOnlyAccess(true)
                    .addWildcardDomain("string")
                    .build()
            )
        assertThat(inferencePipelineRetrieveResponse.workspaceId())
            .contains("055fddb1-261f-4654-8598-f6347ee46a09")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val inferencePipelineRetrieveResponse =
            InferencePipelineRetrieveResponse.builder()
                .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .dateLastEvaluated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .dateLastSampleReceived(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .dateOfNextEvaluation(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                .description("This pipeline is used for production.")
                .failingGoalCount(1L)
                .links(
                    InferencePipelineRetrieveResponse.Links.builder()
                        .app(
                            "https://app.openlayer.com/myWorkspace/3fa85f64-5717-4562-b3fc-2c963f66afa6/inference-pipeline/3fa85f64-5717-4562-b3fc-2c963f66afa6"
                        )
                        .build()
                )
                .name("production")
                .passingGoalCount(5L)
                .projectId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                .status(InferencePipelineRetrieveResponse.Status.COMPLETED)
                .statusMessage("Tests successfully evaluated")
                .totalGoalCount(6L)
                .dataBackend(
                    InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend.builder()
                        .backendType(
                            InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend
                                .BackendType
                                .BIGQUERY
                        )
                        .bigqueryConnectionId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .config(
                            InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend.Config
                                .builder()
                                .groundTruthColumnName("ground_truth")
                                .humanFeedbackColumnName("human_feedback")
                                .inferenceIdColumnName("id")
                                .latencyColumnName("latency")
                                .timestampColumnName("timestamp")
                                .build()
                        )
                        .datasetId("my-dataset")
                        .projectId("my-project")
                        .tableId("my-table")
                        .partitionType(
                            InferencePipelineRetrieveResponse.DataBackend.BigQueryDataBackend
                                .PartitionType
                                .DAY
                        )
                        .build()
                )
                .dateLastPolled(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .project(
                    InferencePipelineRetrieveResponse.Project.builder()
                        .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .creatorId("589ece63-49a2-41b4-98e1-10547761d4b0")
                        .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .developmentGoalCount(5L)
                        .goalCount(10L)
                        .inferencePipelineCount(1L)
                        .links(
                            InferencePipelineRetrieveResponse.Project.Links.builder()
                                .app(
                                    "https://app.openlayer.com/myWorkspace/3fa85f64-5717-4562-b3fc-2c963f66afa6"
                                )
                                .build()
                        )
                        .monitoringGoalCount(5L)
                        .name("My Project")
                        .source(InferencePipelineRetrieveResponse.Project.Source.WEB)
                        .taskType(InferencePipelineRetrieveResponse.Project.TaskType.LLM_BASE)
                        .versionCount(2L)
                        .workspaceId("055fddb1-261f-4654-8598-f6347ee46a09")
                        .description("My project description.")
                        .gitRepo(
                            InferencePipelineRetrieveResponse.Project.GitRepo.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .dateConnected(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .dateUpdated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .gitAccountId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .gitId(0L)
                                .name("name")
                                .private_(true)
                                .projectId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .slug("slug")
                                .url("url")
                                .branch("branch")
                                .rootDir("rootDir")
                                .build()
                        )
                        .build()
                )
                .totalRecordsCount(1000L)
                .workspace(
                    InferencePipelineRetrieveResponse.Workspace.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .creatorId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .dateCreated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dateUpdated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .inviteCount(0L)
                        .memberCount(0L)
                        .name("Openlayer")
                        .periodEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .periodStartDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .projectCount(0L)
                        .slug("openlayer")
                        .status(InferencePipelineRetrieveResponse.Workspace.Status.ACTIVE)
                        .inviteCode("inviteCode")
                        .addMonthlyUsage(
                            InferencePipelineRetrieveResponse.Workspace.MonthlyUsage.builder()
                                .executionTimeMs(0L)
                                .monthYear(LocalDate.parse("2019-12-27"))
                                .predictionCount(0L)
                                .build()
                        )
                        .samlOnlyAccess(true)
                        .addWildcardDomain("string")
                        .build()
                )
                .workspaceId("055fddb1-261f-4654-8598-f6347ee46a09")
                .build()

        val roundtrippedInferencePipelineRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(inferencePipelineRetrieveResponse),
                jacksonTypeRef<InferencePipelineRetrieveResponse>(),
            )

        assertThat(roundtrippedInferencePipelineRetrieveResponse)
            .isEqualTo(inferencePipelineRetrieveResponse)
    }
}
