// File generated from our OpenAPI spec by Stainless.

package com.openlayer.api.models.tests

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.openlayer.api.core.JsonValue
import com.openlayer.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TestListResultsResponseTest {

    @Test
    fun create() {
        val testListResultsResponse =
            TestListResultsResponse.builder()
                .addItem(
                    TestListResultsResponse.Item.builder()
                        .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateDataEnds(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateDataStarts(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .inferencePipelineId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .projectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .status(TestListResultsResponse.Item.Status.PASSING)
                        .statusMessage("Test successfully processed.")
                        .addExpectedValue(
                            TestListResultsResponse.Item.ExpectedValue.builder()
                                .lowerThreshold(0.0f)
                                .measurement("measurement")
                                .upperThreshold(0.0f)
                                .build()
                        )
                        .goal(
                            TestListResultsResponse.Item.Goal.builder()
                                .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                                .commentCount(0L)
                                .creatorId("589ece63-49a2-41b4-98e1-10547761d4b0")
                                .dateArchived(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .description(
                                    JsonValue.from(
                                        "This test checks for duplicate rows in the dataset."
                                    )
                                )
                                .name("No duplicate rows")
                                .number(1L)
                                .originProjectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                                .subtype(
                                    TestListResultsResponse.Item.Goal.Subtype.DUPLICATE_ROW_COUNT
                                )
                                .suggested(false)
                                .addThreshold(
                                    TestListResultsResponse.Item.Goal.Threshold.builder()
                                        .insightName(
                                            TestListResultsResponse.Item.Goal.Threshold.InsightName
                                                .DUPLICATE_ROW_COUNT
                                        )
                                        .addInsightParameter(
                                            TestListResultsResponse.Item.Goal.Threshold
                                                .InsightParameter
                                                .builder()
                                                .name("column_name")
                                                .value(JsonValue.from("Age"))
                                                .build()
                                        )
                                        .measurement("duplicateRowCount")
                                        .operator(
                                            TestListResultsResponse.Item.Goal.Threshold.Operator
                                                .LESS_OR_EQUALS
                                        )
                                        .thresholdMode(
                                            TestListResultsResponse.Item.Goal.Threshold
                                                .ThresholdMode
                                                .AUTOMATIC
                                        )
                                        .value(0.0)
                                        .build()
                                )
                                .type(TestListResultsResponse.Item.Goal.Type.INTEGRITY)
                                .archived(false)
                                .delayWindow(0.0)
                                .evaluationWindow(3600.0)
                                .usesMlModel(false)
                                .usesProductionData(false)
                                .usesReferenceDataset(false)
                                .usesTrainingDataset(false)
                                .usesValidationDataset(true)
                                .build()
                        )
                        .goalId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .rows(
                            "https://api.openlayer.com/v1/versions/3fa85f64-5717-4562-b3fc-2c963f66afa6/rows?label=validation"
                        )
                        .rowsBody(
                            TestListResultsResponse.Item.RowsBody.builder()
                                .addColumnFilter(
                                    TestListResultsResponse.Item.RowsBody.ColumnFilter
                                        .SetColumnFilter
                                        .builder()
                                        .measurement("openlayer_token_set")
                                        .operator(
                                            TestListResultsResponse.Item.RowsBody.ColumnFilter
                                                .SetColumnFilter
                                                .Operator
                                                .CONTAINS_NONE
                                        )
                                        .addValue("cat")
                                        .build()
                                )
                                .addExcludeRowIdList(0L)
                                .addNotSearchQueryAnd("string")
                                .addNotSearchQueryOr("string")
                                .addRowIdList(0L)
                                .addSearchQueryAnd("string")
                                .addSearchQueryOr("string")
                                .build()
                        )
                        .build()
                )
                .lastUnskippedResult(
                    TestListResultsResponse.LastUnskippedResult.builder()
                        .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateDataEnds(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateDataStarts(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .inferencePipelineId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .projectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .status(TestListResultsResponse.LastUnskippedResult.Status.PASSING)
                        .statusMessage("Test successfully processed.")
                        .addExpectedValue(
                            TestListResultsResponse.LastUnskippedResult.ExpectedValue.builder()
                                .lowerThreshold(0.0f)
                                .measurement("measurement")
                                .upperThreshold(0.0f)
                                .build()
                        )
                        .goal(
                            TestListResultsResponse.LastUnskippedResult.Goal.builder()
                                .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                                .commentCount(0L)
                                .creatorId("589ece63-49a2-41b4-98e1-10547761d4b0")
                                .dateArchived(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .description(
                                    JsonValue.from(
                                        "This test checks for duplicate rows in the dataset."
                                    )
                                )
                                .name("No duplicate rows")
                                .number(1L)
                                .originProjectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                                .subtype(
                                    TestListResultsResponse.LastUnskippedResult.Goal.Subtype
                                        .DUPLICATE_ROW_COUNT
                                )
                                .suggested(false)
                                .addThreshold(
                                    TestListResultsResponse.LastUnskippedResult.Goal.Threshold
                                        .builder()
                                        .insightName(
                                            TestListResultsResponse.LastUnskippedResult.Goal
                                                .Threshold
                                                .InsightName
                                                .DUPLICATE_ROW_COUNT
                                        )
                                        .addInsightParameter(
                                            TestListResultsResponse.LastUnskippedResult.Goal
                                                .Threshold
                                                .InsightParameter
                                                .builder()
                                                .name("column_name")
                                                .value(JsonValue.from("Age"))
                                                .build()
                                        )
                                        .measurement("duplicateRowCount")
                                        .operator(
                                            TestListResultsResponse.LastUnskippedResult.Goal
                                                .Threshold
                                                .Operator
                                                .LESS_OR_EQUALS
                                        )
                                        .thresholdMode(
                                            TestListResultsResponse.LastUnskippedResult.Goal
                                                .Threshold
                                                .ThresholdMode
                                                .AUTOMATIC
                                        )
                                        .value(0.0)
                                        .build()
                                )
                                .type(
                                    TestListResultsResponse.LastUnskippedResult.Goal.Type.INTEGRITY
                                )
                                .archived(false)
                                .delayWindow(0.0)
                                .evaluationWindow(3600.0)
                                .usesMlModel(false)
                                .usesProductionData(false)
                                .usesReferenceDataset(false)
                                .usesTrainingDataset(false)
                                .usesValidationDataset(true)
                                .build()
                        )
                        .goalId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .rows(
                            "https://api.openlayer.com/v1/versions/3fa85f64-5717-4562-b3fc-2c963f66afa6/rows?label=validation"
                        )
                        .rowsBody(
                            TestListResultsResponse.LastUnskippedResult.RowsBody.builder()
                                .addColumnFilter(
                                    TestListResultsResponse.LastUnskippedResult.RowsBody
                                        .ColumnFilter
                                        .SetColumnFilter
                                        .builder()
                                        .measurement("openlayer_token_set")
                                        .operator(
                                            TestListResultsResponse.LastUnskippedResult.RowsBody
                                                .ColumnFilter
                                                .SetColumnFilter
                                                .Operator
                                                .CONTAINS_NONE
                                        )
                                        .addValue("cat")
                                        .build()
                                )
                                .addExcludeRowIdList(0L)
                                .addNotSearchQueryAnd("string")
                                .addNotSearchQueryOr("string")
                                .addRowIdList(0L)
                                .addSearchQueryAnd("string")
                                .addSearchQueryOr("string")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(testListResultsResponse.items())
            .containsExactly(
                TestListResultsResponse.Item.builder()
                    .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .dateDataEnds(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .dateDataStarts(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .inferencePipelineId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .projectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .status(TestListResultsResponse.Item.Status.PASSING)
                    .statusMessage("Test successfully processed.")
                    .addExpectedValue(
                        TestListResultsResponse.Item.ExpectedValue.builder()
                            .lowerThreshold(0.0f)
                            .measurement("measurement")
                            .upperThreshold(0.0f)
                            .build()
                    )
                    .goal(
                        TestListResultsResponse.Item.Goal.builder()
                            .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                            .commentCount(0L)
                            .creatorId("589ece63-49a2-41b4-98e1-10547761d4b0")
                            .dateArchived(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                            .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                            .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                            .description(
                                JsonValue.from(
                                    "This test checks for duplicate rows in the dataset."
                                )
                            )
                            .name("No duplicate rows")
                            .number(1L)
                            .originProjectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                            .subtype(TestListResultsResponse.Item.Goal.Subtype.DUPLICATE_ROW_COUNT)
                            .suggested(false)
                            .addThreshold(
                                TestListResultsResponse.Item.Goal.Threshold.builder()
                                    .insightName(
                                        TestListResultsResponse.Item.Goal.Threshold.InsightName
                                            .DUPLICATE_ROW_COUNT
                                    )
                                    .addInsightParameter(
                                        TestListResultsResponse.Item.Goal.Threshold.InsightParameter
                                            .builder()
                                            .name("column_name")
                                            .value(JsonValue.from("Age"))
                                            .build()
                                    )
                                    .measurement("duplicateRowCount")
                                    .operator(
                                        TestListResultsResponse.Item.Goal.Threshold.Operator
                                            .LESS_OR_EQUALS
                                    )
                                    .thresholdMode(
                                        TestListResultsResponse.Item.Goal.Threshold.ThresholdMode
                                            .AUTOMATIC
                                    )
                                    .value(0.0)
                                    .build()
                            )
                            .type(TestListResultsResponse.Item.Goal.Type.INTEGRITY)
                            .archived(false)
                            .delayWindow(0.0)
                            .evaluationWindow(3600.0)
                            .usesMlModel(false)
                            .usesProductionData(false)
                            .usesReferenceDataset(false)
                            .usesTrainingDataset(false)
                            .usesValidationDataset(true)
                            .build()
                    )
                    .goalId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .rows(
                        "https://api.openlayer.com/v1/versions/3fa85f64-5717-4562-b3fc-2c963f66afa6/rows?label=validation"
                    )
                    .rowsBody(
                        TestListResultsResponse.Item.RowsBody.builder()
                            .addColumnFilter(
                                TestListResultsResponse.Item.RowsBody.ColumnFilter.SetColumnFilter
                                    .builder()
                                    .measurement("openlayer_token_set")
                                    .operator(
                                        TestListResultsResponse.Item.RowsBody.ColumnFilter
                                            .SetColumnFilter
                                            .Operator
                                            .CONTAINS_NONE
                                    )
                                    .addValue("cat")
                                    .build()
                            )
                            .addExcludeRowIdList(0L)
                            .addNotSearchQueryAnd("string")
                            .addNotSearchQueryOr("string")
                            .addRowIdList(0L)
                            .addSearchQueryAnd("string")
                            .addSearchQueryOr("string")
                            .build()
                    )
                    .build()
            )
        assertThat(testListResultsResponse.lastUnskippedResult())
            .contains(
                TestListResultsResponse.LastUnskippedResult.builder()
                    .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .dateDataEnds(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .dateDataStarts(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                    .inferencePipelineId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .projectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .status(TestListResultsResponse.LastUnskippedResult.Status.PASSING)
                    .statusMessage("Test successfully processed.")
                    .addExpectedValue(
                        TestListResultsResponse.LastUnskippedResult.ExpectedValue.builder()
                            .lowerThreshold(0.0f)
                            .measurement("measurement")
                            .upperThreshold(0.0f)
                            .build()
                    )
                    .goal(
                        TestListResultsResponse.LastUnskippedResult.Goal.builder()
                            .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                            .commentCount(0L)
                            .creatorId("589ece63-49a2-41b4-98e1-10547761d4b0")
                            .dateArchived(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                            .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                            .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                            .description(
                                JsonValue.from(
                                    "This test checks for duplicate rows in the dataset."
                                )
                            )
                            .name("No duplicate rows")
                            .number(1L)
                            .originProjectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                            .subtype(
                                TestListResultsResponse.LastUnskippedResult.Goal.Subtype
                                    .DUPLICATE_ROW_COUNT
                            )
                            .suggested(false)
                            .addThreshold(
                                TestListResultsResponse.LastUnskippedResult.Goal.Threshold.builder()
                                    .insightName(
                                        TestListResultsResponse.LastUnskippedResult.Goal.Threshold
                                            .InsightName
                                            .DUPLICATE_ROW_COUNT
                                    )
                                    .addInsightParameter(
                                        TestListResultsResponse.LastUnskippedResult.Goal.Threshold
                                            .InsightParameter
                                            .builder()
                                            .name("column_name")
                                            .value(JsonValue.from("Age"))
                                            .build()
                                    )
                                    .measurement("duplicateRowCount")
                                    .operator(
                                        TestListResultsResponse.LastUnskippedResult.Goal.Threshold
                                            .Operator
                                            .LESS_OR_EQUALS
                                    )
                                    .thresholdMode(
                                        TestListResultsResponse.LastUnskippedResult.Goal.Threshold
                                            .ThresholdMode
                                            .AUTOMATIC
                                    )
                                    .value(0.0)
                                    .build()
                            )
                            .type(TestListResultsResponse.LastUnskippedResult.Goal.Type.INTEGRITY)
                            .archived(false)
                            .delayWindow(0.0)
                            .evaluationWindow(3600.0)
                            .usesMlModel(false)
                            .usesProductionData(false)
                            .usesReferenceDataset(false)
                            .usesTrainingDataset(false)
                            .usesValidationDataset(true)
                            .build()
                    )
                    .goalId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .rows(
                        "https://api.openlayer.com/v1/versions/3fa85f64-5717-4562-b3fc-2c963f66afa6/rows?label=validation"
                    )
                    .rowsBody(
                        TestListResultsResponse.LastUnskippedResult.RowsBody.builder()
                            .addColumnFilter(
                                TestListResultsResponse.LastUnskippedResult.RowsBody.ColumnFilter
                                    .SetColumnFilter
                                    .builder()
                                    .measurement("openlayer_token_set")
                                    .operator(
                                        TestListResultsResponse.LastUnskippedResult.RowsBody
                                            .ColumnFilter
                                            .SetColumnFilter
                                            .Operator
                                            .CONTAINS_NONE
                                    )
                                    .addValue("cat")
                                    .build()
                            )
                            .addExcludeRowIdList(0L)
                            .addNotSearchQueryAnd("string")
                            .addNotSearchQueryOr("string")
                            .addRowIdList(0L)
                            .addSearchQueryAnd("string")
                            .addSearchQueryOr("string")
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val testListResultsResponse =
            TestListResultsResponse.builder()
                .addItem(
                    TestListResultsResponse.Item.builder()
                        .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateDataEnds(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateDataStarts(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .inferencePipelineId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .projectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .status(TestListResultsResponse.Item.Status.PASSING)
                        .statusMessage("Test successfully processed.")
                        .addExpectedValue(
                            TestListResultsResponse.Item.ExpectedValue.builder()
                                .lowerThreshold(0.0f)
                                .measurement("measurement")
                                .upperThreshold(0.0f)
                                .build()
                        )
                        .goal(
                            TestListResultsResponse.Item.Goal.builder()
                                .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                                .commentCount(0L)
                                .creatorId("589ece63-49a2-41b4-98e1-10547761d4b0")
                                .dateArchived(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .description(
                                    JsonValue.from(
                                        "This test checks for duplicate rows in the dataset."
                                    )
                                )
                                .name("No duplicate rows")
                                .number(1L)
                                .originProjectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                                .subtype(
                                    TestListResultsResponse.Item.Goal.Subtype.DUPLICATE_ROW_COUNT
                                )
                                .suggested(false)
                                .addThreshold(
                                    TestListResultsResponse.Item.Goal.Threshold.builder()
                                        .insightName(
                                            TestListResultsResponse.Item.Goal.Threshold.InsightName
                                                .DUPLICATE_ROW_COUNT
                                        )
                                        .addInsightParameter(
                                            TestListResultsResponse.Item.Goal.Threshold
                                                .InsightParameter
                                                .builder()
                                                .name("column_name")
                                                .value(JsonValue.from("Age"))
                                                .build()
                                        )
                                        .measurement("duplicateRowCount")
                                        .operator(
                                            TestListResultsResponse.Item.Goal.Threshold.Operator
                                                .LESS_OR_EQUALS
                                        )
                                        .thresholdMode(
                                            TestListResultsResponse.Item.Goal.Threshold
                                                .ThresholdMode
                                                .AUTOMATIC
                                        )
                                        .value(0.0)
                                        .build()
                                )
                                .type(TestListResultsResponse.Item.Goal.Type.INTEGRITY)
                                .archived(false)
                                .delayWindow(0.0)
                                .evaluationWindow(3600.0)
                                .usesMlModel(false)
                                .usesProductionData(false)
                                .usesReferenceDataset(false)
                                .usesTrainingDataset(false)
                                .usesValidationDataset(true)
                                .build()
                        )
                        .goalId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .rows(
                            "https://api.openlayer.com/v1/versions/3fa85f64-5717-4562-b3fc-2c963f66afa6/rows?label=validation"
                        )
                        .rowsBody(
                            TestListResultsResponse.Item.RowsBody.builder()
                                .addColumnFilter(
                                    TestListResultsResponse.Item.RowsBody.ColumnFilter
                                        .SetColumnFilter
                                        .builder()
                                        .measurement("openlayer_token_set")
                                        .operator(
                                            TestListResultsResponse.Item.RowsBody.ColumnFilter
                                                .SetColumnFilter
                                                .Operator
                                                .CONTAINS_NONE
                                        )
                                        .addValue("cat")
                                        .build()
                                )
                                .addExcludeRowIdList(0L)
                                .addNotSearchQueryAnd("string")
                                .addNotSearchQueryOr("string")
                                .addRowIdList(0L)
                                .addSearchQueryAnd("string")
                                .addSearchQueryOr("string")
                                .build()
                        )
                        .build()
                )
                .lastUnskippedResult(
                    TestListResultsResponse.LastUnskippedResult.builder()
                        .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateDataEnds(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateDataStarts(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                        .inferencePipelineId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .projectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .status(TestListResultsResponse.LastUnskippedResult.Status.PASSING)
                        .statusMessage("Test successfully processed.")
                        .addExpectedValue(
                            TestListResultsResponse.LastUnskippedResult.ExpectedValue.builder()
                                .lowerThreshold(0.0f)
                                .measurement("measurement")
                                .upperThreshold(0.0f)
                                .build()
                        )
                        .goal(
                            TestListResultsResponse.LastUnskippedResult.Goal.builder()
                                .id("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                                .commentCount(0L)
                                .creatorId("589ece63-49a2-41b4-98e1-10547761d4b0")
                                .dateArchived(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .dateCreated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .dateUpdated(OffsetDateTime.parse("2024-03-22T11:31:01.185Z"))
                                .description(
                                    JsonValue.from(
                                        "This test checks for duplicate rows in the dataset."
                                    )
                                )
                                .name("No duplicate rows")
                                .number(1L)
                                .originProjectVersionId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                                .subtype(
                                    TestListResultsResponse.LastUnskippedResult.Goal.Subtype
                                        .DUPLICATE_ROW_COUNT
                                )
                                .suggested(false)
                                .addThreshold(
                                    TestListResultsResponse.LastUnskippedResult.Goal.Threshold
                                        .builder()
                                        .insightName(
                                            TestListResultsResponse.LastUnskippedResult.Goal
                                                .Threshold
                                                .InsightName
                                                .DUPLICATE_ROW_COUNT
                                        )
                                        .addInsightParameter(
                                            TestListResultsResponse.LastUnskippedResult.Goal
                                                .Threshold
                                                .InsightParameter
                                                .builder()
                                                .name("column_name")
                                                .value(JsonValue.from("Age"))
                                                .build()
                                        )
                                        .measurement("duplicateRowCount")
                                        .operator(
                                            TestListResultsResponse.LastUnskippedResult.Goal
                                                .Threshold
                                                .Operator
                                                .LESS_OR_EQUALS
                                        )
                                        .thresholdMode(
                                            TestListResultsResponse.LastUnskippedResult.Goal
                                                .Threshold
                                                .ThresholdMode
                                                .AUTOMATIC
                                        )
                                        .value(0.0)
                                        .build()
                                )
                                .type(
                                    TestListResultsResponse.LastUnskippedResult.Goal.Type.INTEGRITY
                                )
                                .archived(false)
                                .delayWindow(0.0)
                                .evaluationWindow(3600.0)
                                .usesMlModel(false)
                                .usesProductionData(false)
                                .usesReferenceDataset(false)
                                .usesTrainingDataset(false)
                                .usesValidationDataset(true)
                                .build()
                        )
                        .goalId("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .rows(
                            "https://api.openlayer.com/v1/versions/3fa85f64-5717-4562-b3fc-2c963f66afa6/rows?label=validation"
                        )
                        .rowsBody(
                            TestListResultsResponse.LastUnskippedResult.RowsBody.builder()
                                .addColumnFilter(
                                    TestListResultsResponse.LastUnskippedResult.RowsBody
                                        .ColumnFilter
                                        .SetColumnFilter
                                        .builder()
                                        .measurement("openlayer_token_set")
                                        .operator(
                                            TestListResultsResponse.LastUnskippedResult.RowsBody
                                                .ColumnFilter
                                                .SetColumnFilter
                                                .Operator
                                                .CONTAINS_NONE
                                        )
                                        .addValue("cat")
                                        .build()
                                )
                                .addExcludeRowIdList(0L)
                                .addNotSearchQueryAnd("string")
                                .addNotSearchQueryOr("string")
                                .addRowIdList(0L)
                                .addSearchQueryAnd("string")
                                .addSearchQueryOr("string")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedTestListResultsResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(testListResultsResponse),
                jacksonTypeRef<TestListResultsResponse>(),
            )

        assertThat(roundtrippedTestListResultsResponse).isEqualTo(testListResultsResponse)
    }
}
