// File generated from our OpenAPI spec by Stainless.

package com.openlayer.api.models.governance.rulestats

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.openlayer.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RuleStatRetrieveResponseTest {

    @Test
    fun create() {
        val ruleStatRetrieveResponse =
            RuleStatRetrieveResponse.builder()
                .ruleResults(
                    RuleStatRetrieveResponse.RuleResults.builder()
                        .total(0L)
                        .totalDueSoon(0L)
                        .totalError(0L)
                        .totalFailing(0L)
                        .totalPassing(0L)
                        .totalPending(0L)
                        .totalRunning(0L)
                        .totalSkipped(0L)
                        .byRuleScope(
                            RuleStatRetrieveResponse.RuleResults.ByRuleScope.builder()
                                .project(
                                    RuleStatRetrieveResponse.RuleResults.ByRuleScope.Project
                                        .builder()
                                        .total(0L)
                                        .totalDueSoon(0L)
                                        .totalError(0L)
                                        .totalFailing(0L)
                                        .totalPassing(0L)
                                        .totalPending(0L)
                                        .totalRunning(0L)
                                        .totalSkipped(0L)
                                        .build()
                                )
                                .workspace(
                                    RuleStatRetrieveResponse.RuleResults.ByRuleScope.Workspace
                                        .builder()
                                        .total(0L)
                                        .totalDueSoon(0L)
                                        .totalError(0L)
                                        .totalFailing(0L)
                                        .totalPassing(0L)
                                        .totalPending(0L)
                                        .totalRunning(0L)
                                        .totalSkipped(0L)
                                        .build()
                                )
                                .build()
                        )
                        .byRuleType(
                            RuleStatRetrieveResponse.RuleResults.ByRuleType.builder()
                                .evidence(
                                    RuleStatRetrieveResponse.RuleResults.ByRuleType.Evidence
                                        .builder()
                                        .total(0L)
                                        .totalDueSoon(0L)
                                        .totalError(0L)
                                        .totalFailing(0L)
                                        .totalPassing(0L)
                                        .totalPending(0L)
                                        .totalRunning(0L)
                                        .totalSkipped(0L)
                                        .build()
                                )
                                .platform(
                                    RuleStatRetrieveResponse.RuleResults.ByRuleType.Platform
                                        .builder()
                                        .total(0L)
                                        .totalDueSoon(0L)
                                        .totalError(0L)
                                        .totalFailing(0L)
                                        .totalPassing(0L)
                                        .totalPending(0L)
                                        .totalRunning(0L)
                                        .totalSkipped(0L)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .rules(
                    RuleStatRetrieveResponse.Rules.builder()
                        .byScope(
                            RuleStatRetrieveResponse.Rules.ByScope.builder()
                                .project(0L)
                                .workspace(0L)
                                .build()
                        )
                        .byType(
                            RuleStatRetrieveResponse.Rules.ByType.builder()
                                .evidence(0L)
                                .platform(0L)
                                .build()
                        )
                        .total(0L)
                        .build()
                )
                .build()

        assertThat(ruleStatRetrieveResponse.ruleResults())
            .isEqualTo(
                RuleStatRetrieveResponse.RuleResults.builder()
                    .total(0L)
                    .totalDueSoon(0L)
                    .totalError(0L)
                    .totalFailing(0L)
                    .totalPassing(0L)
                    .totalPending(0L)
                    .totalRunning(0L)
                    .totalSkipped(0L)
                    .byRuleScope(
                        RuleStatRetrieveResponse.RuleResults.ByRuleScope.builder()
                            .project(
                                RuleStatRetrieveResponse.RuleResults.ByRuleScope.Project.builder()
                                    .total(0L)
                                    .totalDueSoon(0L)
                                    .totalError(0L)
                                    .totalFailing(0L)
                                    .totalPassing(0L)
                                    .totalPending(0L)
                                    .totalRunning(0L)
                                    .totalSkipped(0L)
                                    .build()
                            )
                            .workspace(
                                RuleStatRetrieveResponse.RuleResults.ByRuleScope.Workspace.builder()
                                    .total(0L)
                                    .totalDueSoon(0L)
                                    .totalError(0L)
                                    .totalFailing(0L)
                                    .totalPassing(0L)
                                    .totalPending(0L)
                                    .totalRunning(0L)
                                    .totalSkipped(0L)
                                    .build()
                            )
                            .build()
                    )
                    .byRuleType(
                        RuleStatRetrieveResponse.RuleResults.ByRuleType.builder()
                            .evidence(
                                RuleStatRetrieveResponse.RuleResults.ByRuleType.Evidence.builder()
                                    .total(0L)
                                    .totalDueSoon(0L)
                                    .totalError(0L)
                                    .totalFailing(0L)
                                    .totalPassing(0L)
                                    .totalPending(0L)
                                    .totalRunning(0L)
                                    .totalSkipped(0L)
                                    .build()
                            )
                            .platform(
                                RuleStatRetrieveResponse.RuleResults.ByRuleType.Platform.builder()
                                    .total(0L)
                                    .totalDueSoon(0L)
                                    .totalError(0L)
                                    .totalFailing(0L)
                                    .totalPassing(0L)
                                    .totalPending(0L)
                                    .totalRunning(0L)
                                    .totalSkipped(0L)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(ruleStatRetrieveResponse.rules())
            .isEqualTo(
                RuleStatRetrieveResponse.Rules.builder()
                    .byScope(
                        RuleStatRetrieveResponse.Rules.ByScope.builder()
                            .project(0L)
                            .workspace(0L)
                            .build()
                    )
                    .byType(
                        RuleStatRetrieveResponse.Rules.ByType.builder()
                            .evidence(0L)
                            .platform(0L)
                            .build()
                    )
                    .total(0L)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val ruleStatRetrieveResponse =
            RuleStatRetrieveResponse.builder()
                .ruleResults(
                    RuleStatRetrieveResponse.RuleResults.builder()
                        .total(0L)
                        .totalDueSoon(0L)
                        .totalError(0L)
                        .totalFailing(0L)
                        .totalPassing(0L)
                        .totalPending(0L)
                        .totalRunning(0L)
                        .totalSkipped(0L)
                        .byRuleScope(
                            RuleStatRetrieveResponse.RuleResults.ByRuleScope.builder()
                                .project(
                                    RuleStatRetrieveResponse.RuleResults.ByRuleScope.Project
                                        .builder()
                                        .total(0L)
                                        .totalDueSoon(0L)
                                        .totalError(0L)
                                        .totalFailing(0L)
                                        .totalPassing(0L)
                                        .totalPending(0L)
                                        .totalRunning(0L)
                                        .totalSkipped(0L)
                                        .build()
                                )
                                .workspace(
                                    RuleStatRetrieveResponse.RuleResults.ByRuleScope.Workspace
                                        .builder()
                                        .total(0L)
                                        .totalDueSoon(0L)
                                        .totalError(0L)
                                        .totalFailing(0L)
                                        .totalPassing(0L)
                                        .totalPending(0L)
                                        .totalRunning(0L)
                                        .totalSkipped(0L)
                                        .build()
                                )
                                .build()
                        )
                        .byRuleType(
                            RuleStatRetrieveResponse.RuleResults.ByRuleType.builder()
                                .evidence(
                                    RuleStatRetrieveResponse.RuleResults.ByRuleType.Evidence
                                        .builder()
                                        .total(0L)
                                        .totalDueSoon(0L)
                                        .totalError(0L)
                                        .totalFailing(0L)
                                        .totalPassing(0L)
                                        .totalPending(0L)
                                        .totalRunning(0L)
                                        .totalSkipped(0L)
                                        .build()
                                )
                                .platform(
                                    RuleStatRetrieveResponse.RuleResults.ByRuleType.Platform
                                        .builder()
                                        .total(0L)
                                        .totalDueSoon(0L)
                                        .totalError(0L)
                                        .totalFailing(0L)
                                        .totalPassing(0L)
                                        .totalPending(0L)
                                        .totalRunning(0L)
                                        .totalSkipped(0L)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .rules(
                    RuleStatRetrieveResponse.Rules.builder()
                        .byScope(
                            RuleStatRetrieveResponse.Rules.ByScope.builder()
                                .project(0L)
                                .workspace(0L)
                                .build()
                        )
                        .byType(
                            RuleStatRetrieveResponse.Rules.ByType.builder()
                                .evidence(0L)
                                .platform(0L)
                                .build()
                        )
                        .total(0L)
                        .build()
                )
                .build()

        val roundtrippedRuleStatRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(ruleStatRetrieveResponse),
                jacksonTypeRef<RuleStatRetrieveResponse>(),
            )

        assertThat(roundtrippedRuleStatRetrieveResponse).isEqualTo(ruleStatRetrieveResponse)
    }
}
